
moveset = {
	"bug":{"Bug Bite"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Bug Buzz"		:{"power":90,"accuracy":100,"PP":10,"type":"bug"},
		   "Fury Cutter"	:{"power":40,"accuracy":95,"PP":20,"type":"bug"},
		   "Leech Life"		:{"power":80,"accuracy":100,"PP":10,"type":"bug"},
		   "Megahorn"		:{"power":120,"accuracy":85,"PP":10,"type":"bug"},
		   "Pin Missile"	:{"power":25,"accuracy":95,"PP":20,"type":"bug"},
		   "Signal Beam"	:{"power":75,"accuracy":100,"PP":15,"type":"bug"},
		   "Silver Wind"	:{"power":60,"accuracy":100,"PP":5,"type":"bug"},
		   "String Shot"	:{"power":0,"accuracy":95,"PP":40,"type":"bug"},
		   "Struggle Bug"	:{"power":50,"accuracy":100,"PP":20,"type":"bug"},
		   "Twineedle"		:{"power":25,"accuracy":100,"PP":20,"type":"bug"},
		   "U-turn"			:{"power":70,"accuracy":100,"PP":20,"type":"bug"},
		   "X-Scissor"		:{"power":80,"accuracy":100,"PP":15,"type":"bug"}},

	"dark":{"Bite"			:{"power":60,"accuracy":100,"PP":25,"type":"dark"},
		   "Crunch"			:{"power":80,"accuracy":100,"PP":15,"type":"dark"},
		   "Fake Tears"		:{"power":0,"accuracy":100,"PP":20,"type":"dark"},
		   "Faint Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Knock Off"		:{"power":65,"accuracy":100,"PP":20,"type":"dark"},
		   "Memento"		:{"power":0,"accuracy":100,"PP":10,"type":"dark"},
		   "Pursuit"		:{"power":40,"accuracy":100,"PP":20,"type":"dark"},
		   "Sucker Punch"	:{"power":70,"accuracy":100,"PP":5,"type":"dark"},
		   "Thief"			:{"power":60,"accuracy":100,"PP":25,"type":"dark"},
		   "Throat Chop"	:{"power":80,"accuracy":100,"PP":15,"type":"dark"}},

	"dragon":{"Dragon Breath"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Claw"		:{"power":80,"accuracy":100,"PP":15,"type":"dragon"},
		   "Dragon Dance"		:{"power":0,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Hammer"		:{"power":90,"accuracy":100,"PP":15,"type":"dragon"},
		   "Dragon Pulse"		:{"power":85,"accuracy":100,"PP":10,"type":"dragon"},
		   "Dragon Rage"		:{"power":0,"accuracy":100,"PP":10,"type":"dragon"},
		   "Dual Chop"			:{"power":40,"accuracy":90,"PP":15,"type":"dragon"},
		   "Outrage"			:{"power":120,"accuracy":100,"PP":10,"type":"dragon"},
		   "Dragon Rush"		:{"power":100,"accuracy":75,"PP":10,"type":"dragon"},
		   "Dragon Tail"		:{"power":60,"accuracy":90,"PP":10,"type":"dragon"}},

	"electric":{"Discharge"	:{"power":80,"accuracy":100,"PP":15,"type":"electric"},
		   "Shock Wave"		:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Spark"			:{"power":65,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunder"		:{"power":110,"accuracy":70,"PP":10,"type":"electric"},
		   "Thunder Fang"	:{"power":65,"accuracy":95,"PP":15,"type":"electric"},
		   "Thunder Shock"	:{"power":40,"accuracy":100,"PP":30,"type":"electric"},
		   "Thunder Wave"	:{"power":0,"accuracy":90,"PP":20,"type":"electric"},
		   "Thunderbolt"	:{"power":90,"accuracy":100,"PP":15,"type":"electric"},
		   "Volt Tackle"	:{"power":120,"accuracy":100,"PP":15,"type":"electric"},
		   "Zap Cannon"		:{"power":120,"accuracy":50,"PP":5,"type":"electric"}},

	"fairy":{"Charm"		:{"power":0,"accuracy":100,"PP":20,"type":"fairy"},
		   "Moonlight"		:{"power":0,"accuracy":100,"PP":5,"type":"fairy"},
		   "Sweet Kiss"		:{"power":0,"accuracy":75,"PP":10,"type":"fairy"},
		   "Dazzling Gleam"	:{"power":80,"accuracy":100,"PP":10,"type":"fairy"},
		   "Fairy Wind"		:{"power":40,"accuracy":100,"PP":30,"type":"fairy"},
		   "Moonblast"		:{"power":95,"accuracy":100,"PP":15,"type":"fairy"},
		   "Play Rough"		:{"power":90,"accuracy":90,"PP":10,"type":"fairy"},
		   "Disarming Voice"	:{"power":40,"accuracy":100,"PP":15,"type":"fairy"},
		   "Baby-Doll Eyes"	:{"power":0,"accuracy":100,"PP":30,"type":"fairy"},
		   "Sparkly Swirl"	:{"power":90,"accuracy":100,"PP":15,"type":"fairy"}},

	"fighting":{"Arm Thrust"	:{"power":15,"accuracy":100,"PP":20,"type":"fighting"},
		   "Brick Break"	:{"power":75,"accuracy":100,"PP":15,"type":"fighting"},
		   "Bulk Up"		:{"power":0,"accuracy":100,"PP":20,"type":"fighting"},
		   "Cross Chop"		:{"power":100,"accuracy":80,"PP":5,"type":"fighting"},
		   "Double Kick"	:{"power":30,"accuracy":100,"PP":30,"type":"fighting"},
		   "Dynamic Punch"	:{"power":100,"accuracy":50,"PP":5,"type":"fighting"},
		   "Karate Chop"	:{"power":50,"accuracy":100,"PP":25,"type":"fighting"},
		   "Rock Smash"		:{"power":40,"accuracy":100,"PP":15,"type":"fighting"},
		   "Sky Uppercut"	:{"power":85,"accuracy":90,"PP":15,"type":"fighting"},
		   "Vital Throw"	:{"power":70,"accuracy":100,"PP":10,"type":"fighting"}},

	"fire":{"Blaze Kick"		:{"power":85,"accuracy":90,"PP":10,"type":"fire"},
		   "Ember"		:{"power":40,"accuracy":100,"PP":25,"type":"fire"},
		   "Fire Blast"		:{"power":110,"accuracy":85,"PP":5,"type":"fire"},
		   "Fire Fang"		:{"power":65,"accuracy":95,"PP":15,"type":"fire"},
		   "Fire Punch"		:{"power":75,"accuracy":100,"PP":15,"type":"fire"},
		   "Flame Wheel"	:{"power":60,"accuracy":100,"PP":25,"type":"fire"},
		   "Flamethrower"	:{"power":90,"accuracy":100,"PP":15,"type":"fire"},
		   "Overheat"		:{"power":130,"accuracy":90,"PP":5,"type":"fire"},
		   "Will-O-Wisp"	:{"power":0,"accuracy":85,"PP":15,"type":"fire"},
		   "Sacred Fire"	:{"power":100,"accuracy":95,"PP":5,"type":"fire"}},

	"flying":{"Aerial Ace"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Aeroblast"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Air Cutter"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Drill Peck"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Gust"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Peck"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Wing Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Roost"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Feather Dance"	:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Tailwind"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"}},	

	"ghost":{"Astonish"		:{"power":30,"accuracy":100,"PP":15,"type":"ghost"},
		   "Hex"		:{"power":65,"accuracy":100,"PP":10,"type":"ghost"},
		   "Lick"		:{"power":30,"accuracy":100,"PP":30,"type":"ghost"},
		   "Shadow Ball"	:{"power":80,"accuracy":100,"PP":15,"type":"ghost"},
		   "Shadow Bone"	:{"power":85,"accuracy":100,"PP":10,"type":"ghost"},
		   "Shadow Claw"	:{"power":70,"accuracy":100,"PP":5,"type":"ghost"},
		   "Shadow Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Spirit Shackle"	:{"power":80,"accuracy":100,"PP":10,"type":"ghost"},
		   "Moongeist Beam"	:{"power":100,"accuracy":100,"PP":5,"type":"ghost"},
		   "Destiny Bond"	:{"power":0,"accuracy":100,"PP":5,"type":"ghost"}},

	"grass":{"Absorb"		:{"power":20,"accuracy":100,"PP":25,"type":"grass"},
		   "Bullet Seed"	:{"power":25,"accuracy":100,"PP":30,"type":"grass"},
		   "Giga Drain"		:{"power":75,"accuracy":100,"PP":10,"type":"grass"},
		   "Ingrain"		:{"power":0,"accuracy":100,"PP":20,"type":"grass"},
		   "Leaf Blade"		:{"power":90,"accuracy":100,"PP":15,"type":"grass"},
		   "Leech Seed"		:{"power":0,"accuracy":90,"PP":10,"type":"grass"},
		   "Magical Leaf"	:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Mega Drain"		:{"power":40,"accuracy":100,"PP":15,"type":"grass"},
		   "Razor Leaf"		:{"power":55,"accuracy":95,"PP":25,"type":"grass"},
		   "Synthesis"		:{"power":0,"accuracy":100,"PP":5,"type":"grass"}},

	"ground":{"Earthquake"		:{"power":100,"accuracy":100,"PP":10,"type":"ground"},
		   "Magnitude"		:{"power":0,"accuracy":100,"PP":30,"type":"ground"},
		   "Mud Shot"		:{"power":55,"accuracy":95,"PP":15,"type":"ground"},
		   "Mud-Slap"		:{"power":20,"accuracy":100,"PP":10,"type":"ground"},
		   "Sand Attack"	:{"power":0,"accuracy":100,"PP":15,"type":"ground"},
		   "Bonemerang"		:{"power":50,"accuracy":90,"PP":10,"type":"ground"},
		   "Bone Rush"		:{"power":25,"accuracy":90,"PP":10,"type":"ground"},
		   "Bone Club"		:{"power":65,"accuracy":85,"PP":20,"type":"ground"},
		   "Earth Power"	:{"power":90,"accuracy":100,"PP":10,"type":"ground"},
		   "Fissure"		:{"power":10000,"accuracy":30,"PP":5,"type":"ground"}},

	"ice":{"Aurora Beam"		:{"power":65,"accuracy":100,"PP":20,"type":"ice"},
		   "Blizzard"		:{"power":110,"accuracy":70,"PP":5,"type":"ice"},
		   "Ice Ball"		:{"power":30,"accuracy":90,"PP":20,"type":"ice"},
		   "Ice Beam"		:{"power":90,"accuracy":100,"PP":10,"type":"ice"},
		   "Ice Punch"		:{"power":75,"accuracy":100,"PP":15,"type":"ice"},
		   "Icy Wind"		:{"power":55,"accuracy":95,"PP":15,"type":"ice"},
		   "Powder Snow"	:{"power":40,"accuracy":100,"PP":25,"type":"ice"},
		   "Sheer Cold"		:{"power":10000,"accuracy":30,"PP":5,"type":"ice"},
		   "Ice Hammer"		:{"power":100,"accuracy":90,"PP":10,"type":"ice"},
		   "Avalanche"		:{"power":60,"accuracy":100,"PP":10,"type":"ice"}},

	"normal":{"Belly Drum"		:{"power":0,"accuracy":100,"PP":10,"type":"normal"},
		   "Body Slam"		:{"power":85,"accuracy":100,"PP":15,"type":"normal"},
		   "Cut"		:{"power":50,"accuracy":95,"PP":30,"type":"normal"},
		   "Defense Curl"	:{"power":0,"accuracy":100,"PP":40,"type":"normal"},
		   "Dizzy Punch"	:{"power":70,"accuracy":100,"PP":10,"type":"normal"},
		   "Double Slap"	:{"power":15,"accuracy":85,"PP":10,"type":"normal"},
		   "Double-Edge"	:{"power":120,"accuracy":100,"PP":15,"type":"normal"},
		   "Flail"		:{"power":0,"accuracy":100,"PP":15,"type":"normal"},
		   "Fury Attack"	:{"power":15,"accuracy":85,"PP":20,"type":"normal"},
		   "Horn Drill"		:{"power":10000,"accuracy":30,"PP":5,"type":"normal"}},

	"poison":{"Acid"		:{"power":40,"accuracy":100,"PP":30,"type":"poison"},
		   "Acid Armor"		:{"power":0,"accuracy":100,"PP":20,"type":"poison"},
		   "Poison Fang"	:{"power":50,"accuracy":100,"PP":15,"type":"poison"},
		   "Poison Sting"	:{"power":15,"accuracy":100,"PP":35,"type":"poison"},
		   "Sludge"		:{"power":65,"accuracy":100,"PP":20,"type":"poison"},
		   "Sludge Bomb"	:{"power":90,"accuracy":100,"PP":10,"type":"poison"},
		   "Smog"		:{"power":30,"accuracy":70,"PP":20,"type":"poison"},
		   "Toxic"		:{"power":0,"accuracy":90,"PP":10,"type":"poison"},
		   "Poison Powder"	:{"power":0,"accuracy":75,"PP":35,"type":"poison"},
		   "Poison Tail"	:{"power":50,"accuracy":100,"PP":25,"type":"poison"}},

	"psychic":{"Agility"		:{"power":0,"accuracy":100,"PP":30,"type":"psychic"},
		   "Confusion"		:{"power":50,"accuracy":100,"PP":25,"type":"psychic"},
		   "Heal Pulse"		:{"power":0,"accuracy":100,"PP":10,"type":"psychic"},
		   "Psybeam"		:{"power":65,"accuracy":100,"PP":20,"type":"psychic"},
		   "Psychic"		:{"power":90,"accuracy":100,"PP":10,"type":"psychic"},
		   "Psycho Boost"	:{"power":140,"accuracy":90,"PP":5,"type":"psychic"},
		   "Extrasensory"	:{"power":80,"accuracy":100,"PP":20,"type":"psychic"},
		   "Meditate"		:{"power":0,"accuracy":100,"PP":40,"type":"psychic"},
		   "Kinesis"		:{"power":0,"accuracy":80,"PP":15,"type":"psychic"},
		   "Heart Stamp"	:{"power":60,"accuracy":100,"PP":25,"type":"psychic"}},

	"rock":{"Ancient Power"		:{"power":60,"accuracy":100,"PP":5,"type":"rock"},
		   "Rock Blast"		:{"power":25,"accuracy":90,"PP":10,"type":"rock"},
		   "Rock Slide"		:{"power":75,"accuracy":90,"PP":10,"type":"rock"},
		   "Rollout"		:{"power":30,"accuracy":90,"PP":20,"type":"rock"},
		   "Rock Throw"		:{"power":50,"accuracy":90,"PP":15,"type":"rock"},
		   "Rock Polish"	:{"power":0,"accuracy":100,"PP":20,"type":"rock"},
		   "Accelerock"		:{"power":40,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Tomb"		:{"power":60,"accuracy":95,"PP":15,"type":"rock"},
		   "Smack Down"		:{"power":50,"accuracy":100,"PP":15,"type":"rock"},
		   "Head Smash"		:{"power":150,"accuracy":80,"PP":5,"type":"rock"}},

	"steel":{"Iron Defense"		:{"power":0,"accuracy":100,"PP":15,"type":"steel"},
		   "Iron Tail"		:{"power":100,"accuracy":75,"PP":15,"type":"steel"},
		   "Metal Claw"		:{"power":50,"accuracy":95,"PP":35,"type":"steel"},
		   "Steel Wing"		:{"power":70,"accuracy":90,"PP":25,"type":"steel"},
		   "Bullet Punch"	:{"power":40,"accuracy":100,"PP":30,"type":"steel"},
		   "Magnet Bomb"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Meteor Mash"	:{"power":90,"accuracy":90,"PP":10,"type":"steel"},
		   "Smart Strike"	:{"power":70,"accuracy":100,"PP":10,"type":"steel"},
		   "Anchor Shot"	:{"power":80,"accuracy":100,"PP":20,"type":"steel"},
		   "Autotomize"		:{"power":0,"accuracy":100,"PP":15,"type":"steel"}},

	"water":{"Bubble"		:{"power":40,"accuracy":100,"PP":30,"type":"water"},
		   "Bubble Beam"	:{"power":65,"accuracy":100,"PP":20,"type":"water"},
		   "Crabhammer"		:{"power":100,"accuracy":90,"PP":10,"type":"water"},
		   "Hydro Pump"		:{"power":110,"accuracy":80,"PP":5,"type":"water"},
		   "Muddy Water"	:{"power":90,"accuracy":85,"PP":10,"type":"water"},
		   "Surf"		:{"power":90,"accuracy":100,"PP":15,"type":"water"},
		   "Water Pulse"	:{"power":80,"accuracy":100,"PP":15,"type":"water"},
		   "Waterfall"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Withdraw"		:{"power":0,"accuracy":100,"PP":40,"type":"water"},
		   "Steam Eruption"	:{"power":110,"accuracy":95,"PP":5,"type":"water"}}
}
# movelist = list(moveset["water"].items())
# moves = []
# desc = []
# for i in movelist:
# 	moves.append(i[0])
# 	desc.append(i[1])
# r_number = 4

# move = moves[r_number]
# print(desc[r_number]["accuracy"])
