
moveset = {
	"bug":{"Bug Bite"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Bug Buzz"		:{"power":90,"accuracy":100,"PP":10,"type":"bug"},
		   "Fury Cutter"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Leech Life"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Megahorn"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Pin Missile"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Signal Beam"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Silver Wind"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "String Shot"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Struggle Bug"	:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "Twineedle"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "U-turn"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"},
		   "X-Scissor"		:{"power":60,"accuracy":100,"PP":20,"type":"bug"}},

	"dark":{"Bite"			:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Crunch"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Fake Tears"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Faint Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Knock Off"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Memento"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Pursuit"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Sucker Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Thief"		:{"power":60,"accuracy":100,"PP":20,"type":"dark"},
		   "Throat Chop"	:{"power":60,"accuracy":100,"PP":20,"type":"dark"}},

	"dragon":{"Dragon Breath"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Claw"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Dance"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Hammer"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Pulse"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Rage"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dual Chop"		:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Outrage"		:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Rush"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"},
		   "Dragon Tail"	:{"power":60,"accuracy":100,"PP":20,"type":"dragon"}},

	"electric":{"Discharge"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Shock Wave"		:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Spark"		:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunder"		:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunder Fang"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunder Shock"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunder Wave"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Thunderbolt"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Volt Tackle"	:{"power":60,"accuracy":100,"PP":20,"type":"electric"},
		   "Zap Cannon"		:{"power":60,"accuracy":100,"PP":20,"type":"electric"}},

	"fairy":{"Charm"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Moonlight"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Sweet Kiss"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Dazzling Gleam"	:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Fairy Wind"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Moonblast"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Play Rough"		:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Disarming Voice"	:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Baby-Doll Eyes"	:{"power":60,"accuracy":100,"PP":20,"type":"fairy"},
		   "Sparkly Swirl"	:{"power":60,"accuracy":100,"PP":20,"type":"fairy"}},

	"fighting":{"Arm Thrust"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Brick Break"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Bulk Up"		:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Cross Chop"		:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Double Kick"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Dynamic Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Karate Chop"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Rock Smash"		:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Sky Uppercut"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"},
		   "Vital Throw"	:{"power":60,"accuracy":100,"PP":20,"type":"fighting"}},

	"fire":{"Blaze Kick"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Ember"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Fire Blast"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Fire Fang"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Fire Punch"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Flame Wheel"	:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Flamethrower"	:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Overheat"		:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Will-O-Wisp"	:{"power":60,"accuracy":100,"PP":20,"type":"fire"},
		   "Sacred Fire"	:{"power":60,"accuracy":100,"PP":20,"type":"fire"}},

	"flying":{"Aerial Ace"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Aeroblast"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Air Cutter"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Drill Peck"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Gust"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Peck"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Wing Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Roost"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Feather Dance"	:{"power":60,"accuracy":100,"PP":20,"type":"flying"},
		   "Tailwind"		:{"power":60,"accuracy":100,"PP":20,"type":"flying"}},	

	"ghost":{"Astonish"		:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Hex"		:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Lick"		:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Shadow Ball"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Shadow Bone"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Shadow Claw"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Shadow Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Spirit Shackle"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Moongeist Beam"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"},
		   "Destiny Bond"	:{"power":60,"accuracy":100,"PP":20,"type":"ghost"}},

	"grass":{"Absorb"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Bullet Seed"	:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Giga Drain"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Ingrain"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Leaf Blade"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Leech Seed"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Magical Leaf"	:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Mega Drain"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Razor Leaf"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"},
		   "Synthesis"		:{"power":60,"accuracy":100,"PP":20,"type":"grass"}},

	"ground":{"Earthquake"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Magnitude"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Mud Shot"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Mud-Slap"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Sand Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Bonemerang"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Bone Rush"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Bone Club"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Earth Power"	:{"power":60,"accuracy":100,"PP":20,"type":"ground"},
		   "Fissure"		:{"power":60,"accuracy":100,"PP":20,"type":"ground"}},

	"ice":{"Aurora Beam"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Blizzard"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Ice Ball"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Ice Beam"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Ice Punch"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Icy Wind"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Powder Snow"	:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Sheer Cold"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Ice Hammer"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"},
		   "Avalanche"		:{"power":60,"accuracy":100,"PP":20,"type":"ice"}},

	"normal":{"Belly Drum"		:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Body Slam"		:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Cut"		:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Defense Curl"	:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Dizzy Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Double Slap"	:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Double-Edge"	:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Flail"		:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Fury Attack"	:{"power":60,"accuracy":100,"PP":20,"type":"normal"},
		   "Horn Drill"		:{"power":60,"accuracy":100,"PP":20,"type":"normal"}},

	"poison":{"Acid"		:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Acid Armor"		:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Poison Fang"	:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Poison Sting"	:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Sludge"		:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Sludge Bomb"	:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Smog"		:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Toxic"		:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Poison Powder"	:{"power":60,"accuracy":100,"PP":20,"type":"poison"},
		   "Poison Tail"	:{"power":60,"accuracy":100,"PP":20,"type":"poison"}},

	"psychic":{"Agility"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Confusion"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Heal Pulse"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Psybeam"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Psychic"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Psycho Boost"	:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Extrasensory"	:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Meditate"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Kinesis"		:{"power":60,"accuracy":100,"PP":20,"type":"psychic"},
		   "Heart Stamp"	:{"power":60,"accuracy":100,"PP":20,"type":"psychic"}},

	"rock":{"Ancient Power"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Blast"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Slide"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rollout"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Throw"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Polish"	:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Accelerock"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Rock Tomb"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Smack Down"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"},
		   "Head Smash"		:{"power":60,"accuracy":100,"PP":20,"type":"rock"}},

	"steel":{"Iron Defense"		:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Iron Tail"		:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Metal Claw"		:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Steel Wing"		:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Bullet Punch"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Magnet Bomb"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Meteor Mash"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Smart Strike"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Anchor Shot"	:{"power":60,"accuracy":100,"PP":20,"type":"steel"},
		   "Autotomize"		:{"power":60,"accuracy":100,"PP":20,"type":"steel"}},

	"water":{"Bubble"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Bubble Beam"	:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Crabhammer"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Hydro Pump"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Muddy Water"	:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Surf"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Water Pulse"	:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Waterfall"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Withdraw"		:{"power":60,"accuracy":100,"PP":20,"type":"water"},
		   "Steam Eruption"	:{"power":60,"accuracy":100,"PP":20,"type":"water"}}
}